# Generated by Django 2.1.7 on 2019-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
