# Generated by Django 2.1.7 on 2019-03-30 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_auto_20190326_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
