# Generated by Django 2.1.7 on 2019-04-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20190409_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='external_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
