# Generated by Django 2.1.7 on 2019-04-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_auto_20190406_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
