# Generated by Django 2.1.7 on 2019-04-06 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_errorlog_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(599)]),
        ),
    ]
